language: php

sudo: required

matrix:
  include:
    - php: 7.3
      env: SW_VERSION="develop"
    - php: 7.4
      env: SW_VERSION="develop"
    - php: master
      env: SW_VERSION="develop"

  allow_failures:
    - php: master

addons:
  apt:
    packages:
      - valgrind

before_install:
  - export PHP_MAJOR="$(`phpenv which php` -r 'echo phpversion();' | cut -d '.' -f 1)"
  - export PHP_MINOR="$(`phpenv which php` -r 'echo phpversion();' | cut -d '.' -f 2)"
  - echo $PHP_MAJOR
  - echo $PHP_MINOR

install:
  - cd $TRAVIS_BUILD_DIR
  - bash ./tests/swow.install.sh
  - phpenv config-rm xdebug.ini || echo "xdebug not available"
  - phpenv config-add ./tests/ci.ini
  - USE_ZEND_ALLOC=0 valgrind php --ri swow

before_script:
  - cd $TRAVIS_BUILD_DIR
  - composer update -o
  - cp ./.github/workflows/Dockerfile Dockerfile && docker build . -t swow:latest
  - docker run --entrypoint php -p 9501:9501 -d swow:latest examples/http_server.php
  - docker run --entrypoint php -p 9502:9502 -d swow:latest examples/tcp_server.php

script:
  - composer analyse
  - composer test
